server {
    listen 80;
    listen 443 ssl;
    server_name nother.one;

    ssl_certificate /etc/nginx/ssl/nother.one.crt;
    ssl_certificate_key /etc/nginx/ssl/nother.one.key;

    location / {
        root /var/www/html;
        index index.html;
    }
}

server {
    listen 80;
    server_name test.local;

    location / {
        root /var/www/html;
        index index.html;
    }
}
